import type { Category, Quiz } from "./quiz-types"

export const seedCategories: Category[] = [
  {
    id: "cat-khmer",
    name: "Khmer Language / អក្សរសាស្ត្រខ្មែរ",
    description: "Khmer language and literature courses",
    color: "#3b82f6", // blue
  },
  {
    id: "cat-math",
    name: "Mathematics / គណិតវិទ្យា",
    description: "Mathematics courses for all grade levels",
    color: "#10b981", // green
  },
  {
    id: "cat-science",
    name: "Science / វិទ្យាសាស្ត្រ",
    description: "General science courses",
    color: "#8b5cf6", // purple
  },
  {
    id: "cat-general",
    name: "General Knowledge / ចំណេះដឹងទូទៅ",
    description: "General knowledge and mixed subjects",
    color: "#f59e0b", // orange
  },
]

export const seedQuizzes: Quiz[] = [
  // Comprehensive Quiz - All Question Types Demo
  {
    id: "quiz-all-types-demo",
    title: "Complete Question Types Demo - All 11 Types",
    titleKm: "ការបង្ហាញប្រភេទសំណួរទាំងអស់ - ទាំង ១១ ប្រភេទ",
    description: "This comprehensive quiz demonstrates all 11 question types with at least 2 examples of each type. Perfect for testing and demonstration purposes.",
    descriptionKm: "តេស្តពេញលេញនេះបង្ហាញប្រភេទសំណួរទាំង ១១ ជាមួយឧទាហរណ៍យ៉ាងតិច ២ នៃប្រភេទនីមួយៗ។ ល្អសម្រាប់ការសាកល្បង និងការបង្ហាញ។",
    categoryId: "cat-general",
    gradeLevel: "Grade 3-4 / ថ្នាក់ទី៣-៤",
    subject: "Mixed Subjects",
    examType: "regular",
    passingScore: 60,
    certificateEnabled: true,
    adaptiveTesting: false,
    maxAttempts: 5,
    timeLimit: 60,
    randomizeQuestions: false,
    allowMultipleAttempts: true,
    showCorrectAnswers: true,
    createdBy: "1",
    createdAt: new Date().toISOString(),
    questions: [
      // TYPE 1: Multiple Choice - Question 1
      {
        id: "q-mc-1",
        type: "multiple-choice",
        question: "What is the capital city of Cambodia?",
        questionKm: "តើរដ្ឋធានីនៃប្រទេសកម្ពុជាគឺអ្វី?",
        options: ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville"],
        optionsKm: ["ភ្នំពេញ", "សៀមរាប", "បាត់ដំបង", "ព្រះសីហនុ"],
        correctAnswer: "Phnom Penh",
        points: 5,
        difficulty: "easy",
        explanation: "Phnom Penh is the capital and largest city of Cambodia.",
        explanationKm: "ភ្នំពេញគឺជារដ្ឋធានី និងជាទីក្រុងធំបំផុតនៃប្រទេសកម្ពុជា។",
      },
      // TYPE 1: Multiple Choice - Question 2
      {
        id: "q-mc-2",
        type: "multiple-choice",
        question: "What is 12 × 3?",
        questionKm: "១២ × ៣ = ?",
        options: ["33", "36", "39", "42"],
        optionsKm: ["៣៣", "៣៦", "៣៩", "៤២"],
        correctAnswer: "36",
        points: 5,
        difficulty: "easy",
        explanation: "12 multiplied by 3 equals 36",
        explanationKm: "១២ គុណនឹង ៣ ស្មើនឹង ៣៦",
      },

      // TYPE 2: Multiple Select - Question 1
      {
        id: "q-ms-1",
        type: "multiple-select",
        question: "Which of these are planets in our solar system? (Select all that apply)",
        questionKm: "តើអ្វីខ្លះជាភពក្នុងប្រព័ន្ធព្រះអាទិត្យរបស់យើង? (ជ្រើសរើសទាំងអស់ដែលត្រឹមត្រូវ)",
        options: ["Mars", "Moon", "Venus", "Sun", "Jupiter"],
        optionsKm: ["ភពអង្គារ", "ព្រះច័ន្ទ", "ភពសុក្រ", "ព្រះអាទិត្យ", "ភពព្រហស្បតិ៍"],
        correctAnswer: ["Mars", "Venus", "Jupiter"],
        points: 10,
        difficulty: "medium",
        explanation: "Mars, Venus, and Jupiter are planets. The Moon is a satellite and the Sun is a star.",
        explanationKm: "អង្គារ សុក្រ និង ព្រហស្បតិ៍ ជាភព។ ព្រះច័ន្ទជាផ្កាយរណប ហើយព្រះអាទិត្យជាផ្កាយ។",
      },
      // TYPE 2: Multiple Select - Question 2
      {
        id: "q-ms-2",
        type: "multiple-select",
        question: "Which of these are vowels in English? (Select all that apply)",
        questionKm: "តើអក្ខរៈណាខ្លះជាស្រៈក្នុងភាសាអង់គ្លេស? (ជ្រើសរើសទាំងអស់ដែលត្រឹមត្រូវ)",
        options: ["A", "B", "E", "I", "K", "O", "U"],
        optionsKm: ["A", "B", "E", "I", "K", "O", "U"],
        correctAnswer: ["A", "E", "I", "O", "U"],
        points: 10,
        difficulty: "easy",
        explanation: "The vowels in English are: A, E, I, O, U",
        explanationKm: "ស្រៈក្នុងភាសាអង់គ្លេសគឺ៖ A, E, I, O, U",
      },

      // TYPE 3: True/False - Question 1
      {
        id: "q-tf-1",
        type: "true-false",
        question: "Water boils at 100 degrees Celsius.",
        questionKm: "ទឹកពុះនៅ ១០០ អង្សាសេ។",
        options: ["True", "False"],
        optionsKm: ["ពិត", "មិនពិត"],
        correctAnswer: "True",
        points: 5,
        difficulty: "easy",
        explanation: "Yes, water boils at 100°C at standard atmospheric pressure.",
        explanationKm: "បាទ/ចាស ទឹកពុះនៅ ១០០°C នៅសម្ពាធបរិយាកាសស្តង់ដារ។",
      },
      // TYPE 3: True/False - Question 2
      {
        id: "q-tf-2",
        type: "true-false",
        question: "There are 7 days in a week.",
        questionKm: "មាន ៧ ថ្ងៃក្នុងមួយសប្តាហ៍។",
        options: ["True", "False"],
        optionsKm: ["ពិត", "មិនពិត"],
        correctAnswer: "True",
        points: 5,
        difficulty: "easy",
        explanation: "Correct! A week has 7 days.",
        explanationKm: "ត្រឹមត្រូវ! មួយសប្តាហ៍មាន ៧ ថ្ងៃ។",
      },

      // TYPE 4: Short Answer - Question 1
      {
        id: "q-sa-1",
        type: "short-answer",
        question: "What is the name of the longest river in the world?",
        questionKm: "តើឈ្មោះទន្លេវែងបំផុតក្នុងពិភពលោកគឺអ្វី?",
        correctAnswer: "Nile",
        points: 10,
        difficulty: "medium",
        explanation: "The Nile River in Africa is the longest river in the world.",
        explanationKm: "ទន្លេនីលនៅអាហ្វ្រិកគឺជាទន្លេវែងបំផុតក្នុងពិភពលោក។",
      },
      // TYPE 4: Short Answer - Question 2
      {
        id: "q-sa-2",
        type: "short-answer",
        question: "If a triangle has sides of 3cm, 4cm, and 5cm, what is its perimeter in cm?",
        questionKm: "ប្រសិនបើត្រីកោណមានបួនជុំវិញ ៣សង់ទីម៉ែត្រ ៤សង់ទីម៉ែត្រ និង ៥សង់ទីម៉ែត្រ តើបរិមាត្ររបស់វាប៉ុន្មានសង់ទីម៉ែត្រ?",
        correctAnswer: "12",
        points: 10,
        difficulty: "medium",
        explanation: "Perimeter = 3 + 4 + 5 = 12 cm",
        explanationKm: "បរិមាត្រ = ៣ + ៤ + ៥ = ១២ សង់ទីម៉ែត្រ",
      },

      // TYPE 5: Fill in the Blanks - Question 1
      {
        id: "q-fb-1",
        type: "fill-blanks",
        question: "Complete the sentence:",
        questionKm: "បំពេញប្រយោគ:",
        blanksTemplate: "The capital of France is ___ and the capital of Cambodia is ___.",
        blanksTemplateKm: "រដ្ឋធានីនៃប្រទេសបារាំងគឺ ___ ហើយរដ្ឋធានីនៃប្រទេសកម្ពុជាគឺ ___។",
        blanksCount: 2,
        correctAnswer: ["Paris", "Phnom Penh"],
        points: 10,
        difficulty: "medium",
        explanation: "Paris is the capital of France, and Phnom Penh is the capital of Cambodia.",
        explanationKm: "ប៉ារីសគឺជារដ្ឋធានីនៃប្រទេសបារាំង ហើយភ្នំពេញគឺជារដ្ឋធានីនៃប្រទេសកម្ពុជា។",
      },
      // TYPE 5: Fill in the Blanks - Question 2
      {
        id: "q-fb-2",
        type: "fill-blanks",
        question: "Complete the math equation:",
        questionKm: "បំពេញសមីការគណិតវិទ្យា:",
        blanksTemplate: "10 + ___ = 25, so the missing number is ___",
        blanksTemplateKm: "១០ + ___ = ២៥, ដូច្នេះលេខដែលបាត់គឺ ___",
        blanksCount: 2,
        correctAnswer: ["15", "15"],
        points: 10,
        difficulty: "easy",
        explanation: "10 + 15 = 25",
        explanationKm: "១០ + ១៥ = ២៥",
      },

      // TYPE 6: Drag & Drop - Question 1
      {
        id: "q-dd-1",
        type: "drag-drop",
        question: "Arrange the following animals from smallest to largest:",
        questionKm: "រៀបចំសត្វទាំងនេះពីតូចទៅធំ:",
        options: ["Elephant", "Mouse", "Dog", "Cat"],
        optionsKm: ["ដំរី", "កណ្តុរ", "ឆ្កែ", "ឆ្មា"],
        correctAnswer: ["Mouse", "Cat", "Dog", "Elephant"],
        points: 10,
        difficulty: "easy",
        explanation: "From smallest to largest: Mouse, Cat, Dog, Elephant",
        explanationKm: "ពីតូចទៅធំ៖ កណ្តុរ ឆ្មា ឆ្កែ ដំរី",
      },
      // TYPE 6: Drag & Drop - Question 2
      {
        id: "q-dd-2",
        type: "drag-drop",
        question: "Arrange the seasons in order starting with Spring:",
        questionKm: "រៀបចំរដូវកាលតាមលំដាប់ចាប់ផ្តើមពីរដូវផ្កា:",
        options: ["Winter", "Summer", "Fall", "Spring"],
        optionsKm: ["រដូវរងា", "រដូវក្តៅ", "រដូវស្លឹកឈើជ្រុះ", "រដូវផ្កា"],
        correctAnswer: ["Spring", "Summer", "Fall", "Winter"],
        points: 10,
        difficulty: "easy",
        explanation: "The seasons in order: Spring → Summer → Fall → Winter",
        explanationKm: "រដូវកាលតាមលំដាប់៖ រដូវផ្កា → រដូវក្តៅ → រដូវស្លឹកឈើជ្រុះ → រដូវរងា",
      },

      // TYPE 7: Matching - Question 1
      {
        id: "q-match-1",
        type: "matching",
        question: "Match the colors with their Khmer names:",
        questionKm: "ផ្គូផ្គងពណ៌ជាមួយនឹងឈ្មោះខ្មែររបស់វា:",
        pairs: [
          { left: "Red", right: "ក្រហម", leftKm: "ក្រហម", rightKm: "Red" },
          { left: "Blue", right: "ខៀវ", leftKm: "ខៀវ", rightKm: "Blue" },
          { left: "Green", right: "បៃតង", leftKm: "បៃតង", rightKm: "Green" },
          { left: "Yellow", right: "លឿង", leftKm: "លឿង", rightKm: "Yellow" },
        ],
        correctAnswer: {},
        points: 10,
        difficulty: "medium",
        explanation: "Match the English color names with their Khmer equivalents.",
        explanationKm: "ផ្គូផ្គងឈ្មោះពណ៌ជាភាសាអង់គ្លេសជាមួយនឹងពាក្យខ្មែររបស់វា។",
      },
      // TYPE 7: Matching - Question 2
      {
        id: "q-match-2",
        type: "matching",
        question: "Match the numbers with their words:",
        questionKm: "ផ្គូផ្គងលេខជាមួយនឹងពាក្យ:",
        pairs: [
          { left: "1", right: "One", leftKm: "១", rightKm: "មួយ" },
          { left: "2", right: "Two", leftKm: "២", rightKm: "ពីរ" },
          { left: "3", right: "Three", leftKm: "៣", rightKm: "បី" },
        ],
        correctAnswer: {},
        points: 10,
        difficulty: "easy",
        explanation: "Match numbers with their corresponding words.",
        explanationKm: "ផ្គូផ្គងលេខជាមួយនឹងពាក្យដែលត្រូវគ្នា។",
      },

      // TYPE 8: Ordering/Sequence - Question 1
      {
        id: "q-order-1",
        type: "ordering",
        question: "Put these events in chronological order:",
        questionKm: "ដាក់ព្រឹត្តិការណ៍ទាំងនេះតាមលំដាប់កាលបរិច្ឆេទ:",
        options: ["Wake up", "Eat breakfast", "Go to school", "Sleep"],
        optionsKm: ["ភ្ញាក់ពីគេង", "ញ៉ាំអាហារពេលព្រឹក", "ទៅសាលារៀន", "គេង"],
        correctAnswer: ["Wake up", "Eat breakfast", "Go to school", "Sleep"],
        points: 10,
        difficulty: "easy",
        explanation: "The correct daily routine order.",
        explanationKm: "លំដាប់ទម្លាប់ប្រចាំថ្ងៃត្រឹមត្រូវ។",
      },
      // TYPE 8: Ordering/Sequence - Question 2
      {
        id: "q-order-2",
        type: "ordering",
        question: "Arrange the months in order starting from January:",
        questionKm: "រៀបចំខែតាមលំដាប់ចាប់ផ្តើមពីខែមករា:",
        options: ["March", "January", "April", "February"],
        optionsKm: ["ខែមីនា", "ខែមករា", "ខែមេសា", "ខែកុម្ភៈ"],
        correctAnswer: ["January", "February", "March", "April"],
        points: 10,
        difficulty: "easy",
        explanation: "The correct order of months from January to April.",
        explanationKm: "លំដាប់ត្រឹមត្រូវនៃខែពីខែមករាដល់ខែមេសា។",
      },

      // TYPE 9: Essay - Question 1
      {
        id: "q-essay-1",
        type: "essay",
        question: "Write a short paragraph (3-5 sentences) about your favorite animal and explain why you like it.",
        questionKm: "សរសេរកថាខណ្ឌខ្លី (៣-៥ ប្រយោគ) អំពីសត្វដែលអ្នកចូលចិត្តបំផុត និងពន្យល់ពីមូលហេតុដែលអ្នកចូលចិត្តវា។",
        correctAnswer: "",
        points: 15,
        difficulty: "hard",
        explanation: "Grading criteria: Grammar (5pts), Vocabulary (3pts), Structure (3pts), Content (4pts). Sample answer should name the animal, describe its features, and explain personal reasons for liking it.",
        explanationKm: "លក្ខណៈវិនិច្ឆ័យដាក់ពិន្ទុ៖ វេយ្យាករណ៍ (៥ពិន្ទុ) វាក្យសព្ទ (៣ពិន្ទុ) រចនាសម្ព័ន្ធ (៣ពិន្ទុ) មាតិកា (៤ពិន្ទុ)។ ចម្លើយគំរូគួរតែមានឈ្មោះសត្វ ពណ៌នាលក្ខណៈសម្បត្តិរបស់វា និងពន្យល់ហេតុផលផ្ទាល់ខ្លួន។",
      },
      // TYPE 9: Essay - Question 2
      {
        id: "q-essay-2",
        type: "essay",
        question: "Describe what you did during your last weekend. Write at least 4 sentences.",
        questionKm: "ពណ៌នាអំពីអ្វីដែលអ្នកបានធ្វើក្នុងអំឡុងចុងសប្តាហ៍ចុងក្រោយរបស់អ្នក។ សរសេរយ៉ាងហោចណាស់ ៤ ប្រយោគ។",
        correctAnswer: "",
        points: 15,
        difficulty: "medium",
        explanation: "Answer should include: activities, time references, and details. Grading: Grammar (5pts), Vocabulary (5pts), Content (5pts)",
        explanationKm: "ចម្លើយគួរតែរួមមាន៖ សកម្មភាព ពេលវេលា និងព័ត៌មានលម្អិត។ ការដាក់ពិន្ទុ៖ វេយ្យាករណ៍ (៥ពិន្ទុ) វាក្យសព្ទ (៥ពិន្ទុ) មាតិកា (៥ពិន្ទុ)",
      },

      // TYPE 10: Image Choice - Question 1
      {
        id: "q-img-1",
        type: "image-choice",
        question: "Look at the geometric shape. What shape is this?",
        questionKm: "មើលរូបធរណីមាត្រ។ តើនេះជារូបរាងអ្វី?",
        imageUrl: "https://via.placeholder.com/300x200/FF6B6B/FFFFFF?text=Triangle",
        options: ["Circle", "Triangle", "Square", "Rectangle"],
        optionsKm: ["រង្វង់", "ត្រីកោណ", "ការ៉េ", "ចតុកោណកែង"],
        correctAnswer: "Triangle",
        points: 10,
        difficulty: "easy",
        explanation: "The image shows a triangle - a shape with 3 sides.",
        explanationKm: "រូបភាពបង្ហាញត្រីកោណ - រូបរាងដែលមាន ៣ ជ្រុង។",
      },
      // TYPE 10: Image Choice - Question 2
      {
        id: "q-img-2",
        type: "image-choice",
        question: "What color is shown in the image?",
        questionKm: "តើពណ៌អ្វីត្រូវបានបង្ហាញក្នុងរូបភាព?",
        imageUrl: "https://via.placeholder.com/300x200/4ECDC4/FFFFFF?text=Blue",
        options: ["Red", "Blue", "Green", "Yellow"],
        optionsKm: ["ក្រហម", "ខៀវ", "បៃតង", "លឿង"],
        correctAnswer: "Blue",
        points: 10,
        difficulty: "easy",
        explanation: "The image shows the color blue.",
        explanationKm: "រូបភាពបង្ហាញពណ៌ខៀវ។",
      },

      // TYPE 11: Image Hotspot - Question 1
      {
        id: "q-hot-1",
        type: "hotspot",
        question: "Click on the geometric shapes in the image. Identify all triangles.",
        questionKm: "ចុចលើរូបធរណីមាត្រក្នុងរូបភាព។ កំណត់អត្តសញ្ញាណត្រីកោណទាំងអស់។",
        imageUrl: "https://via.placeholder.com/400x300/95E1D3/FFFFFF?text=Shapes",
        hotspots: [
          { x: 25, y: 25, label: "Triangle 1", labelKm: "ត្រីកោណ ១" },
          { x: 75, y: 75, label: "Triangle 2", labelKm: "ត្រីកោណ ២" },
        ],
        correctAnswer: [],
        points: 15,
        difficulty: "medium",
        explanation: "Click on all the triangular shapes in the image.",
        explanationKm: "ចុចលើរូបរាងត្រីកោណទាំងអស់ក្នុងរូបភាព។",
      },
      // TYPE 11: Image Hotspot - Question 2
      {
        id: "q-hot-2",
        type: "hotspot",
        question: "Click on the parts of a plant. Select the leaf.",
        questionKm: "ចុចលើផ្នែកនៃដើមឈើ។ ជ្រើសរើសសន្លឹក។",
        imageUrl: "https://via.placeholder.com/400x300/F38181/FFFFFF?text=Plant",
        hotspots: [
          { x: 50, y: 30, label: "Leaf", labelKm: "សន្លឹក" },
          { x: 50, y: 80, label: "Root", labelKm: "ឫស" },
        ],
        correctAnswer: [],
        points: 10,
        difficulty: "easy",
        explanation: "Click on the leaf part of the plant.",
        explanationKm: "ចុចលើផ្នែកសន្លឹកនៃដើមឈើ។",
      },
    ],
  },

  // Grade 3 - Khmer Language Quiz
  {
    id: "quiz-khmer-grade3",
    title: "Khmer Reading Comprehension - Grade 3",
    titleKm: "ការយល់អត្ថន័យអត្ថបទ - ថ្នាក់ទី៣",
    description: "Test your understanding of Khmer language basics including reading, vocabulary, and grammar for Grade 3 students.",
    descriptionKm: "ធ្វើតេស្តការយល់ដឹងរបស់អ្នកអំពីមូលដ្ឋានភាសាខ្មែរ រួមមាន ការអាន វាក្យសព្ទ និង វេយ្យាករណ៍ សម្រាប់សិស្សថ្នាក់ទី៣។",
    categoryId: "cat-khmer",
    gradeLevel: "Grade 3 / ថ្នាក់ទី៣",
    subject: "Khmer Language",
    examType: "regular",
    passingScore: 60,
    certificateEnabled: true,
    adaptiveTesting: false,
    maxAttempts: 3,
    timeLimit: 30,
    randomizeQuestions: false,
    allowMultipleAttempts: true,
    showCorrectAnswers: true,
    createdBy: "1",
    createdAt: new Date().toISOString(),
    questions: [
      // Question 1: Multiple Choice
      {
        id: "q-khmer-g3-1",
        type: "multiple-choice",
        question: "Which word means 'school' in Khmer?",
        questionKm: "ពាក្យណាមានន័យថា 'សាលារៀន' ជាភាសាខ្មែរ?",
        options: ["ផ្ទះ", "សាលារៀន", "ទីផ្សារ", "មន្ទីរពេទ្យ"],
        optionsKm: ["ផ្ទះ", "សាលារៀន", "ទីផ្សារ", "មន្ទីរពេទ្យ"],
        correctAnswer: "សាលារៀន",
        points: 10,
        difficulty: "easy",
        explanation: "សាលារៀន means 'school' - a place where students learn.",
        explanationKm: "សាលារៀន មានន័យថា 'សាលារៀន' - កន្លែងដែលសិស្សរៀនសូត្រ។",
      },
      // Question 2: Multiple Select
      {
        id: "q-khmer-g3-2",
        type: "multiple-select",
        question: "Select all the words that are types of fruit:",
        questionKm: "ជ្រើសរើសពាក្យទាំងអស់ដែលជាប្រភេទផ្លែឈើ:",
        options: ["ស្វាយ", "សៀវភៅ", "ចេក", "តុ", "ទន្លាប់"],
        optionsKm: ["ស្វាយ", "សៀវភៅ", "ចេក", "តុ", "ទន្លាប់"],
        correctAnswer: ["ស្វាយ", "ចេក", "ទន្លាប់"],
        points: 15,
        difficulty: "medium",
        explanation: "ស្វាយ (mango), ចេក (banana), and ទន្លាប់ (papaya) are all fruits.",
        explanationKm: "ស្វាយ, ចេក និង ទន្លាប់ ជាផ្លែឈើទាំងអស់។",
      },
      // Question 3: True/False
      {
        id: "q-khmer-g3-3",
        type: "true-false",
        question: "The Khmer alphabet has 33 consonants.",
        questionKm: "អក្ខរក្រមខ្មែរមាន ៣៣ ព្យញ្ជនៈ។",
        options: ["True", "False"],
        optionsKm: ["ពិត", "មិនពិត"],
        correctAnswer: "True",
        points: 10,
        difficulty: "easy",
        explanation: "Yes, the Khmer alphabet contains 33 consonants.",
        explanationKm: "បាទ/ចាស អក្ខរក្រមខ្មែរមាន ៣៣ ព្យញ្ជនៈ។",
      },
      // Question 4: Fill in the Blanks
      {
        id: "q-khmer-g3-4",
        type: "fill-blanks",
        question: "Complete the sentence:",
        questionKm: "បំពេញប្រយោគ:",
        blanksTemplate: "ខ្ញុំចូលចិត្តទៅ___ ដើម្បីរៀនសូត្រ។",
        blanksTemplateKm: "ខ្ញុំចូលចិត្តទៅ___ ដើម្បីរៀនសូត្រ។",
        blanksCount: 1,
        correctAnswer: ["សាលារៀន"],
        points: 10,
        difficulty: "easy",
        explanation: "The sentence means: I like to go to school to study.",
        explanationKm: "ប្រយោគមានន័យថា៖ ខ្ញុំចូលចិត្តទៅសាលារៀន ដើម្បីរៀនសូត្រ។",
      },
      // Question 5: Matching
      {
        id: "q-khmer-g3-5",
        type: "matching",
        question: "Match the Khmer words with their meanings:",
        questionKm: "ផ្គូផ្គងពាក្យខ្មែរជាមួយនឹងអត្ថន័យរបស់វា:",
        pairs: [
          { left: "ព្រះអាទិត្យ", right: "Sun", leftKm: "ព្រះអាទិត្យ", rightKm: "ព្រះអាទិត្យ" },
          { left: "ព្រះច័ន្ទ", right: "Moon", leftKm: "ព្រះច័ន្ទ", rightKm: "ព្រះច័ន្ទ" },
          { left: "ផ្កាយ", right: "Star", leftKm: "ផ្កាយ", rightKm: "ផ្កាយ" },
        ],
        correctAnswer: {},
        points: 15,
        difficulty: "medium",
        explanation: "Basic celestial objects vocabulary in Khmer.",
        explanationKm: "វាក្យសព្ទមូលដ្ឋានអំពីវត្ថុសេឡេស្ទាល់ជាភាសាខ្មែរ។",
      },
    ],
  },

  // Grade 3 - Mathematics Quiz
  {
    id: "quiz-math-grade3",
    title: "Basic Addition and Subtraction - Grade 3",
    titleKm: "ការបូក និង ការដក មូលដ្ឋាន - ថ្នាក់ទី៣",
    description: "Practice basic arithmetic operations including addition and subtraction for Grade 3 students.",
    descriptionKm: "អនុវត្តប្រតិបត្តិការគណិតវិទ្យាមូលដ្ឋាន រួមមាន ការបូក និង ការដក សម្រាប់សិស្សថ្នាក់ទី៣។",
    categoryId: "cat-math",
    gradeLevel: "Grade 3 / ថ្នាក់ទី៣",
    subject: "Mathematics",
    examType: "regular",
    passingScore: 60,
    certificateEnabled: true,
    adaptiveTesting: false,
    maxAttempts: 3,
    timeLimit: 30,
    randomizeQuestions: false,
    allowMultipleAttempts: true,
    showCorrectAnswers: true,
    createdBy: "1",
    createdAt: new Date().toISOString(),
    questions: [
      // Question 1: Multiple Choice
      {
        id: "q-math-g3-1",
        type: "multiple-choice",
        question: "What is 15 + 27?",
        questionKm: "១៥ + ២៧ = ?",
        options: ["40", "42", "43", "45"],
        optionsKm: ["៤០", "៤២", "៤៣", "៤៥"],
        correctAnswer: "42",
        points: 10,
        difficulty: "easy",
        explanation: "15 + 27 = 42",
        explanationKm: "១៥ + ២៧ = ៤២",
      },
      // Question 2: Multiple Choice
      {
        id: "q-math-g3-2",
        type: "multiple-choice",
        question: "What is 50 - 23?",
        questionKm: "៥០ - ២៣ = ?",
        options: ["25", "27", "28", "30"],
        optionsKm: ["២៥", "២៧", "២៨", "៣០"],
        correctAnswer: "27",
        points: 10,
        difficulty: "easy",
        explanation: "50 - 23 = 27",
        explanationKm: "៥០ - ២៣ = ២៧",
      },
      // Question 3: Short Answer
      {
        id: "q-math-g3-3",
        type: "short-answer",
        question: "If you have 8 apples and buy 5 more, how many apples do you have in total?",
        questionKm: "ប្រសិនបើអ្នកមានផ្លែប៉ោម ៈ ហើយទិញបន្ថែមទៀត ៥, អ្នកមានផ្លែប៉ោមសរុបប៉ុន្មាន?",
        correctAnswer: "13",
        points: 15,
        difficulty: "medium",
        explanation: "8 + 5 = 13 apples",
        explanationKm: "៨ + ៥ = ១៣ ផ្លែប៉ោម",
      },
      // Question 4: Fill in the Blanks
      {
        id: "q-math-g3-4",
        type: "fill-blanks",
        question: "Complete the equation:",
        questionKm: "បំពេញសមីការ:",
        blanksTemplate: "25 + ___ = 50",
        blanksTemplateKm: "២៥ + ___ = ៥០",
        blanksCount: 1,
        correctAnswer: ["25"],
        points: 10,
        difficulty: "medium",
        explanation: "25 + 25 = 50",
        explanationKm: "២៥ + ២៥ = ៥០",
      },
      // Question 5: Ordering
      {
        id: "q-math-g3-5",
        type: "ordering",
        question: "Arrange these numbers from smallest to largest:",
        questionKm: "រៀបចំលេខទាំងនេះពីតូចទៅធំ:",
        options: ["15", "8", "23", "12"],
        optionsKm: ["១៥", "៨", "២៣", "១២"],
        correctAnswer: ["8", "12", "15", "23"],
        points: 15,
        difficulty: "medium",
        explanation: "The correct order is: 8, 12, 15, 23",
        explanationKm: "លំដាប់ត្រឹមត្រូវគឺ៖ ៨, ១២, ១៥, ២៣",
      },
    ],
  },

  // Grade 4 - Khmer Language Quiz
  {
    id: "quiz-khmer-grade4",
    title: "Khmer Grammar and Composition - Grade 4",
    titleKm: "វេយ្យាករណ៍ និង ការតែង - ថ្នាក់ទី៤",
    description: "Advanced Khmer language skills including grammar rules, sentence structure, and basic composition for Grade 4 students.",
    descriptionKm: "ជំនាញភាសាខ្មែរកម្រិតខ្ពស់ រួមមាន វេយ្យាករណ៍ រចនាសម្ព័ន្ធប្រយោគ និង ការតែងមូលដ្ឋាន សម្រាប់សិស្សថ្នាក់ទី៤។",
    categoryId: "cat-khmer",
    gradeLevel: "Grade 4 / ថ្នាក់ទី៤",
    subject: "Khmer Language",
    examType: "regular",
    passingScore: 60,
    certificateEnabled: true,
    adaptiveTesting: false,
    maxAttempts: 3,
    timeLimit: 40,
    randomizeQuestions: false,
    allowMultipleAttempts: true,
    showCorrectAnswers: true,
    createdBy: "1",
    createdAt: new Date().toISOString(),
    questions: [
      // Question 1: Multiple Choice
      {
        id: "q-khmer-g4-1",
        type: "multiple-choice",
        question: "Which sentence is grammatically correct?",
        questionKm: "ប្រយោគណាត្រឹមត្រូវតាមវេយ្យាករណ៍?",
        options: [
          "ខ្ញុំទៅសាលារៀននៅព្រឹក",
          "ទៅខ្ញុំសាលារៀននៅព្រឹក",
          "សាលារៀនខ្ញុំទៅព្រឹក",
          "ព្រឹកទៅខ្ញុំសាលារៀន",
        ],
        optionsKm: [
          "ខ្ញុំទៅសាលារៀននៅព្រឹក",
          "ទៅខ្ញុំសាលារៀននៅព្រឹក",
          "សាលារៀនខ្ញុំទៅព្រឹក",
          "ព្រឹកទៅខ្ញុំសាលារៀន",
        ],
        correctAnswer: "ខ្ញុំទៅសាលារៀននៅព្រឹក",
        points: 10,
        difficulty: "medium",
        explanation: "The correct sentence follows Khmer grammar: Subject + Verb + Object + Time",
        explanationKm: "ប្រយោគត្រឹមត្រូវតាមវេយ្យាករណ៍ខ្មែរ៖ ប្រធាន + កិរិយា + កម្ម + ពេលវេលា",
      },
      // Question 2: Multiple Select
      {
        id: "q-khmer-g4-2",
        type: "multiple-select",
        question: "Select all words that are verbs (action words):",
        questionKm: "ជ្រើសរើសពាក្យទាំងអស់ដែលជាកិរិយាសព្ទ:",
        options: ["រត់", "សៀវភៅ", "ញ៉ាំ", "ស្អាត", "សរសេរ"],
        optionsKm: ["រត់", "សៀវភៅ", "ញ៉ាំ", "ស្អាត", "សរសេរ"],
        correctAnswer: ["រត់", "ញ៉ាំ", "សរសេរ"],
        points: 15,
        difficulty: "medium",
        explanation: "រត់ (run), ញ៉ាំ (eat), and សរសេរ (write) are all verbs.",
        explanationKm: "រត់, ញ៉ាំ និង សរសេរ ជាកិរិយាសព្ទទាំងអស់។",
      },
      // Question 3: True/False
      {
        id: "q-khmer-g4-3",
        type: "true-false",
        question: "In Khmer language, adjectives usually come after the noun they describe.",
        questionKm: "ក្នុងភាសាខ្មែរ គុណនាមតែងតែមកបន្ទាប់ពីនាមដែលវាពណ៌នា។",
        options: ["True", "False"],
        optionsKm: ["ពិត", "មិនពិត"],
        correctAnswer: "True",
        points: 10,
        difficulty: "medium",
        explanation: "Yes, in Khmer, adjectives follow nouns (e.g., ផ្ទះធំ = house big)",
        explanationKm: "បាទ/ចាស ក្នុងភាសាខ្មែរ គុណនាមមកបន្ទាប់នាម (ឧទាហរណ៍ ផ្ទះធំ)",
      },
      // Question 4: Fill in the Blanks
      {
        id: "q-khmer-g4-4",
        type: "fill-blanks",
        question: "Complete the proverb:",
        questionKm: "បំពេញសុភាសិត:",
        blanksTemplate: "ឆ្មាចាស់ចាប់___ បាន",
        blanksTemplateKm: "ឆ្មាចាស់ចាប់___ បាន",
        blanksCount: 1,
        correctAnswer: ["កណ្តុរ"],
        points: 15,
        difficulty: "hard",
        explanation: "The proverb is: ឆ្មាចាស់ចាប់កណ្តុរបាន (An old cat can catch rats - experience matters)",
        explanationKm: "សុភាសិតគឺ៖ ឆ្មាចាស់ចាប់កណ្តុរបាន (បទពិសោធន៍មានសារៈសំខាន់)",
      },
      // Question 5: Essay
      {
        id: "q-khmer-g4-5",
        type: "essay",
        question: "Write a short paragraph (3-5 sentences) about your favorite season and why you like it.",
        questionKm: "សរសេរកថាខណ្ឌខ្លី (៣-៥ ប្រយោគ) អំពីរដូវកាលដែលអ្នកចូលចិត្តបំផុត និង មូលហេតុដែលអ្នកចូលចិត្តវា។",
        correctAnswer: "",
        points: 20,
        difficulty: "hard",
        explanation: "Sample answer should include: season name, descriptive details, personal reasons. Grading: grammar (5 pts), vocabulary (5 pts), structure (5 pts), content (5 pts)",
        explanationKm: "ចម្លើយគំរូគួរតែរួមមាន៖ ឈ្មោះរដូវកាល ព័ត៌មានលម្អិត និង ហេតុផលផ្ទាល់ខ្លួន។ ការដាក់ពិន្ទុ៖ វេយ្យាករណ៍ (៥ ពិន្ទុ) វាក្យសព្ទ (៥ ពិន្ទុ) រចនាសម្ព័ន្ធ (៥ ពិន្ទុ) មាតិកា (៥ ពិន្ទុ)",
      },
    ],
  },

  // Grade 4 - Mathematics Quiz
  {
    id: "quiz-math-grade4",
    title: "Multiplication, Division, and Fractions - Grade 4",
    titleKm: "ការគុណ ការចែក និង ប្រភាគ - ថ្នាក់ទី៤",
    description: "Master multiplication, division, and introduction to fractions for Grade 4 students.",
    descriptionKm: "ស្វែងយល់ពីការគុណ ការចែក និង ការណែនាំអំពីប្រភាគ សម្រាប់សិស្សថ្នាក់ទី៤។",
    categoryId: "cat-math",
    gradeLevel: "Grade 4 / ថ្នាក់ទី៤",
    subject: "Mathematics",
    examType: "regular",
    passingScore: 60,
    certificateEnabled: true,
    adaptiveTesting: false,
    maxAttempts: 3,
    timeLimit: 40,
    randomizeQuestions: false,
    allowMultipleAttempts: true,
    showCorrectAnswers: true,
    createdBy: "1",
    createdAt: new Date().toISOString(),
    questions: [
      // Question 1: Multiple Choice
      {
        id: "q-math-g4-1",
        type: "multiple-choice",
        question: "What is 8 × 7?",
        questionKm: "៨ × ៧ = ?",
        options: ["54", "56", "58", "60"],
        optionsKm: ["៥៤", "៥៦", "៥៨", "៦០"],
        correctAnswer: "56",
        points: 10,
        difficulty: "easy",
        explanation: "8 × 7 = 56",
        explanationKm: "៨ × ៧ = ៥៦",
      },
      // Question 2: Multiple Choice
      {
        id: "q-math-g4-2",
        type: "multiple-choice",
        question: "What is 72 ÷ 9?",
        questionKm: "៧២ ÷ ៩ = ?",
        options: ["6", "7", "8", "9"],
        optionsKm: ["៦", "៧", "៨", "៩"],
        correctAnswer: "8",
        points: 10,
        difficulty: "easy",
        explanation: "72 ÷ 9 = 8",
        explanationKm: "៧២ ÷ ៩ = ៨",
      },
      // Question 3: Multiple Choice - Fractions
      {
        id: "q-math-g4-3",
        type: "multiple-choice",
        question: "What is 1/2 + 1/4?",
        questionKm: "១/២ + ១/៤ = ?",
        options: ["1/4", "1/2", "3/4", "1"],
        optionsKm: ["១/៤", "១/២", "៣/៤", "១"],
        correctAnswer: "3/4",
        points: 15,
        difficulty: "medium",
        explanation: "1/2 + 1/4 = 2/4 + 1/4 = 3/4",
        explanationKm: "១/២ + ១/៤ = ២/៤ + ១/៤ = ៣/៤",
      },
      // Question 4: Short Answer
      {
        id: "q-math-g4-4",
        type: "short-answer",
        question: "A rectangle has a length of 12 cm and width of 5 cm. What is its area?",
        questionKm: "ចតុកោណកែងមួយមានប្រវែង ១២ សង់ទីម៉ែត្រ និង ទទឹង ៥ សង់ទីម៉ែត្រ។ តើផ្ទៃរបស់វាប៉ុន្មាន?",
        correctAnswer: "60",
        points: 15,
        difficulty: "medium",
        explanation: "Area = length × width = 12 × 5 = 60 cm²",
        explanationKm: "ផ្ទៃ = ប្រវែង × ទទឹង = ១២ × ៥ = ៦០ សង់ទីម៉ែត្រការ៉េ",
      },
      // Question 5: Drag and Drop
      {
        id: "q-math-g4-5",
        type: "drag-drop",
        question: "Drag the steps in order to solve: 15 × 4",
        questionKm: "អូសជំហានតាមលំដាប់ដើម្បីដោះស្រាយ៖ ១៥ × ៤",
        options: [
          "Break down: (10 + 5) × 4",
          "Multiply: (10 × 4) + (5 × 4)",
          "Calculate: 40 + 20",
          "Answer: 60",
        ],
        optionsKm: [
          "បំបែក៖ (១០ + ៥) × ៤",
          "គុណ៖ (១០ × ៤) + (៥ × ៤)",
          "គណនា៖ ៤០ + ២០",
          "ចម្លើយ៖ ៦០",
        ],
        correctAnswer: [
          "Break down: (10 + 5) × 4",
          "Multiply: (10 × 4) + (5 × 4)",
          "Calculate: 40 + 20",
          "Answer: 60",
        ],
        points: 20,
        difficulty: "hard",
        explanation: "Use the distributive property to break down multiplication into easier steps.",
        explanationKm: "ប្រើលក្ខណៈសម្បត្តិចែកចាយ ដើម្បីបំបែកការគុណទៅជាជំហានងាយស្រួល។",
      },
    ],
  },
]
